# Rails5での開発
FROM 504200935189.dkr.ecr.ap-northeast-1.amazonaws.com/schoo-dev-biz:for-local-dev

# Rails4.2での開発
# FROM 504200935189.dkr.ecr.ap-northeast-1.amazonaws.com/schoo-dev-biz:for-local-dev-rails42